### PR TITLE
Possible additions...

### PR DESCRIPTION
**Pull request by jas-**
I went ahead and forked your NoCSRF project in order contribute additional attack vectors that are (IMHO) crucial to preventing CSRF.

The two additional components of the token are a hashed value of the remote address as well as a hashed value of the browser agent.

Both get validated in the same manner as the time stamping already implemented and I tried to keep the code as similar to yours as possible.

Hope it helps.

*EDIT: You may wish to omit the last three commented 'Added some additional seeding for mt_rand()'. It seems that as of PHP4.2 and up this is no longer needed as mt_rand() does it automatically now. My mistake.

### CODE REVIEW

**Comment by BKcore** [comment]
Actually, this seems a bit overkill since we're already generating a random 32 char string for security purpose. The time slug is only here for expiration control. I don't really see the point in adding the remote addr and user agent.

Furthermore, these two _SERVER variables may vary depending on the server and user agent configuration so I would not advise using them as main token generators.

The best thing to do might be to make these two checks optionnal, maybe with an argument flag or something similar. I'll take a closer look at the implementation soon.

Thank you for your additions.

**Comment by jas-** [comment]
This bit on the same OWASP page you reference states that CSRF extends past simple form verification and/or time outs...

<blockquote>Checking the referrer in the client's HTTP request will prevent CSRF attacks. By ensuring the HTTP request have come from the original site means that the attacks from other sites will not function. It is very common to see referrer checks used on embedded network hardware due to memory limitations. XSS can be used to bypass both referrer and token based checks simultaneously. For instance the Sammy Worm used an XHR to obtain the CSRF token to forge requests.
"Although cross-site request forgery is fundamentally a problem with the web application, not the user, users can help protect their accounts at poorly designed sites by logging off the site before visiting another, or clearing their browser's cookies at the end of each browser session." -http://en.wikipedia.org/wiki/Cross-site_request_forgery#_note-1</blockquote>


By providing simple checks on unique items such as the remote address and browser agent you can verify that each page request (form or not) will be sent to and from the computer originally making the request. Each browser may submit a different string but per client this is a unique variable to said machine thereby helping to ensure replays by another computer.

This page: https://www.owasp.org/index.php/Testing_for_CSRF_%28OWASP-SM-005%29 explains the attack vectors that go beyond simple form verification which is easily scripted with the use of robots parsing the form and gathering the csrf token and re-using it with custom form parameters. By implementing the remote address and browser agent any automated csrf would require those be accurate as well.

I believe the appropriate term is 'session hijacking' or 'session replay' as noted here: https://www.owasp.org/index.php/Session_hijacking_attack

No worries though I thought this project was intended to address both. =)

**Comment by BKcore** [comment]
I totally agree, my point was to integrate those checks as an extra option, not as default behaviour, in order to give the programmer a choice when using the class.

**Comment by jas-** [comment]
Well in that case I am glad it helps some

**Comment by BKcore** [comment]
I just added your proposition to the class as an optionnal extra security. 
https://github.com/BKcore/NoCSRF/commit/348c8b19adf7787202d685bd6225af259a3c0d95

Thank you for your additions.

**Comment by jas-** [comment]
No problem. Glad it helped some. I have been reviewing your Orion framework and have been thinking about adding some functionality to it as well. Have a good afternoon.

**Pull request closed without merging**
